services:
  flask:
    build:
      context: ./flask
    ports:
      - "9000:9000"
    env_file:
      - .env  # Reference the .env file here
    environment:
      - DB_HOST=${DB_HOST}  # Example of directly referencing the env variable
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - FLASK_ENV=development
    volumes:
      - ./flask:/app  # Mount the Flask app directory into the container